export type SessionType = {
    id: string;
    username?: string;
    name: string;
    email: string;
    bio?: string;
    profilePictureUrl?: string;
    coverPhotoUrl?: string;
    verifiedDate?: Date;
    isVerified?: boolean;
    isSuspended?: boolean;
    suspendCount?: number;
    suspendedDate?: Date;
    suspendReason?: string;
    lastLogin?: Date;
    createdAt?: Date;
    updatedAt?: Date;
    googleId?: string;
    twoFactorAuthentication?: boolean;
    isPasswordAvailable?: boolean;
  };